version: "3"
services:
  oio-repo:
    image: openio/repo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    volumes:
      - /home/build/pub:/oiorepodestdir
      - ./openio-repo/test/keyFile:/root/keyFile:ro
  front:
    image: openio/repo-front
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    volumes:
      - /home/build/pub:/usr/share/nginx/html/pub/repo:ro
      - ./openio-repo/test/keyFile.pub:/usr/share/nginx/html/pub/repo/keyFile.pub:ro

